on:
  push:
    paths:
      - 'docs/**'
    branches:
      - master
  pull_request:
    paths:
      - 'docs/**'
    branches:
      - master

jobs:
  docs-build:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    name: ğŸ‘·â€â™€ï¸ Docs successfully build
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_PAGES_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
          skip-publish: true

  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: ğŸš€ Release to GitHub Pages
    env:
      USE_SSH: true
      GIT_USER: ${{ secrets.GH_USERNAME }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_PAGES_TOKEN }}
          deploy-branch: 'gh-pages'
          gatsby-args: --prefix-paths
          git-config-name: 'gh-bot'
          working-dir: 'docs'
      - run: |
          yarn install
          yarn deploy:website
